FROM python:3.8-slim-buster

EXPOSE 8000

ENV PYTHONDONTWRITEBYTECODE=1
COPY requirements.txt .
RUN python -m pip install -r requirements.txt

RUN useradd appuser && mkdir /app && chown -R appuser /app
USER appuser

WORKDIR /app

COPY --chown=appuser . /app/
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]

