version: '3.4'
services:

  db:
    container_name: db_rest_products
    image: "postgres:12.4"
    restart: unless-stopped
    ports: 
      - ${DB_PORT}:${DB_PORT}
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
  pg:
    container_name: pg_rest_products
    image: dpage/pgadmin4
    restart: unless-stopped
    ports:
      - ${PG_PORT}:${PG_PORT}
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PG_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PG_PASSWORD}
  app:
    container_name: app_rest_products
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
    - ./:/app
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - db

volumes:
  pgdata:
